import React from 'react'
import Navbar from "../../components/Utils/Navbar";
import Head from "next/head";
import Footer from "../../components/Utils/Footer";
import Sidebar from '../../components/Utils/Sidebar';

function consultant() {
    return (
        <div>
            <Navbar />
            <Head>
                <title>
                    Carrers | Finovista
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className='eventPostMain'>
                    <div className='my-8'>
                        <h2><strong>Position: Manager / Consultant / Analyst - Program Management</strong></h2>
                        <p><br /></p>
                        <p>Finovista is New Delhi based, an ISO certified firm engaged in Program Management and Consulting firm engaged in
                            IN Country Representation, Program Management Consulting, Capacity Building, and Technology Management.
                            We work extensively with Developmental Agencies, Government Bodies, Research Agencies, and Businesses across
                            over 10 countries in areas of Energy, Clean Cooking, Environment, Innovative Tech, Green Finance, Carbon Finance,
                            Healthcare, Industry 4.0, and Social Enterprise Development.</p>
                        <p><br /></p>
                        <p>With a mission to harness Technology and Innovation to drive the growth of organisations, we offer
                            an integrated suite of services to our agencies. Being new age consulting firm, we bring forth a
                            unique blend of Technical, Managerial and Project Management skill sets, work on three layers
                            structure viz Professional, Expert and Advisor from India &amp; the world, who are extremely capable
                            and experienced in executing complex projects.</p>
                        <p>pThe company is in an early growth stage and is looking to recruit new people who are not afraid of
                            hard work and possess seriousness, responsible, high work ethic, flexibility in hours and
                            understanding the nuances of the early-stage venture. We are looking to hire for our Corporate
                            Office in New Delhi, INDIA.</p>
                        <p>This role is suitable for candidates from a variety of professional backgrounds including those with
                            research, consulting, think-tank and corporate experience.</p>
                        <p><br /></p>
                        <p><strong>Primary Duties or Responsibilities</strong></p>
                        <p><br /></p>
                        <p><strong>Recruitment &amp; Selection</strong></p>
                        <p><br /></p>
                        <ul className='mx-8'>
                            <li>Understand the organization&rsquo;s requirement, find new talent with a pre defined selection process and shortlist them after verification.&nbsp;</li>
                            <li>Share the shortlisted candidates with the management for final selection and schedule interviews.&nbsp;</li>
                            <li>Ensures coordination and facilitation of new hire orientation program to generate a positive first impression for employees.&nbsp;</li>
                            <li>Responsible for end-to-end employee experience from completing joining formalities to induction to exiting process.&nbsp;</li>
                            <li>Establishes and maintains contact with external recruitment agencies to get the suitable candidates&nbsp;</li>
                            <li>Creating Master Information System for all the employees and update the same on regular basis&nbsp;</li>
                            <li>Understand the requirements in consultation with management and develop Job Descripton for the new position/s.&nbsp;</li>
                            <li>Create data base of CVs and update the same on regular basis to fulfil the new openings in the organization.</li>
                        </ul>
                        <p><br /></p>
                        <p><strong>Compensation & Benifits</strong></p>
                        <p><br /></p>
                        <ul className='mx-8'>
                            <li>Maintain employees&rsquo; records, administering benefits and prepare payroll for timely payment of salary.&nbsp;</li>
                            <li>Manage Performance Appraisal, Reward and Recognition program for employees&nbsp;</li>
                            <li>Adding and deleting incoming and outgoing employees respectively to insurance.</li>
                        </ul>
                        <p><br /></p>
                        <p><strong>Skill Knowledge And Abilities</strong></p>
                        <p><br /></p>
                        <ul className='mx-8'>
                            <li>5-7 years HR operations background, preferably working with the consulting/program management consulting firm/service sector/search firms</li>
                            <li>Have experience in working with small consulting firm</li>
                            <li>Having full understanding of working directly with Cofounders and managing right balance between Cofounders and employees&nbsp;</li>
                            <li>Good knowledge and experience in employment law and employee tax knowledge.&nbsp;</li>
                            <li>Sound knowledge of HR policies and practices, various SOPs and implementation&nbsp;</li>
                            <li>Should have network and knowledge to source potential candidates from various offline and online channels (social media and professional platforms) respectively.&nbsp;</li>
                            <li>Should have experience to deal and coordinate with Recruitment and Consulting firm for hiring candidates.&nbsp;</li>
                            <li>Should have ability to judge behavioural skills of the candidates like Time Management, Communication skills, Patience, Self-improvement, Emotional Intelligence, Self-confidence etc.&nbsp;</li>
                            <li>Strong analytical and drafting skills, an eye for detail.</li>
                            <li>Strong interpersonal and communication (both written and oral).</li>
                            <li>Ability to work under pressure, multi-task, establish priorities and solve problems.&nbsp;</li>
                            <li>Good team player and ability to work with senior management team as well as peers.&nbsp;</li>
                            <li>Proficiency in MS Office applications and well verse in Words &amp; Excel&nbsp;</li>
                            <li>Diploma /degree in human resources or related area of study.</li>
                        </ul>
                        <p><br /></p>
                        <p>Finovista operates in a dynamic environment and the candidate will be required to show flexibility in
                            undertaking a variety of tasks.</p>
                        <p><br /></p>
                        <p><strong>Remuneration Competitive remuneration:</strong></p>
                        <p><br /></p>
                        <p>Commensurate to the experience and matching the best of standards adopted by industry or other
                            similar organizations for similar roles.</p>
                        <p><br /></p>
                        <p>Interested candidates are requested to send their applications along with a statement of suitability
                            and current expected CTC at &nbsp;
                            <a href="mailto:sunil.sharma@finovista">
                                sunil.sharma@finovista.
                            </a> Only shortlisted candidates will be
                            contacted. We appreciate your interest.</p>
                            <a href="https://docs.google.com/forms/d/e/1FAIpQLSf7IhcEyKelgQAxerkoMRp0OShposvvQHmw_0oMDXAN0QC_yw/viewform" target='_blank'>
                                <button className='bg-blue-500 border-none cursor-pointer text-white rounded-md px-6 py-4 mt-4'>
                                    Apply Now
                                </button>
                            </a>
                    </div>
                    <div className=''>
                        <Sidebar />
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    )
}

export default consultant;
