import React from 'react'
import Navbar from "../../components/Utils/Navbar";
import Head from "next/head";
import Footer from "../../components/Utils/Footer";
import Sidebar from '../../components/Utils/Sidebar';
function deputyProgramme() {
    return (
        <div>
            <Navbar />
            <Head>
                <title>
                    Carrers | Finovista
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className='eventPostMain'>
                    <div className='my-8'>
                        <h2><strong>Internship - Program Management / Research Work</strong></h2>
                        <p><br /></p>
                        <p>Finovista is New Delhi based, an ISO certified firm engaged in Program Management and Consulting firm
                            engaged in IN Country Representation, Program Management Consulting, Capacity Building and Technology
                            Management. We work extensively with Developmental Agencies, Government Bodies, Research Agencies
                            and Businesses across over 10 countries in areas of Energy, Clean Cooking, Environment, Innovative Tech,
                            Green Finance, Carbon Finance, Healthcare, Industry 4.0 and Social Enterprise Development.</p>
                        <p><br /></p>
                        <p>Finovista is New Delhi based, an ISO certified firm engaged in Program Management and Consulting firm
                            engaged in IN Country Representation, Program Management Consulting, Capacity Building and Technology
                            Management. We work extensively with Developmental Agencies, Government Bodies, Research Agencies
                            and Businesses across over 10 countries in areas of Energy, Clean Cooking, Environment, Innovative Tech,
                            Green Finance, Carbon Finance, Healthcare, Industry 4.0 and Social Enterprise Development.</p>
                        <p><br /></p>
                        <p><strong>Qualifications and Skills</strong></p>
                        <p><br /></p>
                        <ul className='mx-8'>
                            <li>Should currently pursuing a recognised educational programme or should have completed your qualification/degree within a twelve-month period at the time of application in a field related to Finovisat&rsquo;s activities;&nbsp;</li>
                            <li>Should be fluent in English (written and verbal) communication;&nbsp;</li>
                            <li>Willingness to learn and develop the capability to research, write, communicate, facilitate with all levels with government, international agencies, industries, clients and internal staff and management&nbsp;</li>
                            <li>Ability to adapt to a new environment, work in an interdisciplinary and multicultural environment with a high sense of responsibility and deliver under tight deadlines in a professional environment.</li>
                        </ul>
                        <p>Finovista operates in a dynamic environment and the candidate will be required to show flexibility in
                            undertaking a variety of tasks.</p>
                        <p><br /></p>
                        <p><strong>Location</strong></p>
                        <p><br /></p>
                        <p>Mahipalpur, New Delhi 110037</p>
                        <p><br /></p>
                        <p><strong>Duration</strong></p>
                        <p><br /></p>
                        <p>3 – 6 months</p>
                        <p><br /></p>
                        <p><strong>Remuneration</strong></p>
                        <p><br /></p>
                        <p>Stipend within the range of 10k to 15k</p>
                        <p><br /></p>
                        <p>Interested candidates are requested to send their applications along with a statement of suitability
                            and current expected CTC at &nbsp;
                            <a href="mailto:sunil.sharma@finovista">
                                sunil.sharma@finovista.
                            </a> Only shortlisted candidates will be
                            contacted. We appreciate your interest.</p>
                    </div>
                    <div className=''>
                        <Sidebar />
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    )
}

export default deputyProgramme
