import { useRouter } from "next/router";
import Navbar from "../../components/Utils/Navbar";
import Head from "next/head";
import Footer from "../../components/Utils/Footer";
import Sidebar from "../../components/Utils/Sidebar";
import RelatedPost from "../../components/Utils/RelatedPost";
import SinglePost from "../../components/Post/SinglePost";
import { useEffect, useState } from "react";

const programPost = () => {
  const router = useRouter();
  const { slug } = router.query;

  const [categories, setCategories] = useState([]);

  useEffect(() => {
    const getCategory = async () => {
      try {
        const cate = await fetch("/api/category");
        let cateRes = await cate.json();
        setCategories(cateRes.category);
      } catch (error) {
        console.log(error);
      }
    };
    getCategory();
  }, []);

  return (
    <div>
      <Navbar />
      <Head>
        <title>
          {slug ? slug.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ") : "Program Post"} | Finovista
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="eventPostMain">
          <div>
            <SinglePost api='programs' getData='program' />
          </div>
          <div className="">
            <Sidebar />
          </div>
        </div>
        <RelatedPost api='programs' type="programs" link='program' getData='programs' />
        <Footer />
      </div>
    </div>
  );
};

export default programPost;
