import { useRouter, useState } from "next/router";
import Navbar from "../../../components/Utils/Navbar";
import Head from "next/head";
import Footer from "../../../components/Utils/Footer";
import Sidebar from "../../../components/Utils/Sidebar";
import SinglePost from "../../../components/Post/SinglePost";
import SinglePostEvent from '../../../components/Event/SinglePostEvent'


const blogPost = () => {
  const router = useRouter();
  const { route, slug } = router.query;
  const routerData = {
    blog: { api: "posts", getData: "post" },
    program: { api: "programs", getData: "program" },
    service: {api: "services", getData:"service"},
    industry: {api: "industries", getData:"industry"},
    events: {api: "events", getData:"event"}
  }
  return (
    <div>
      <Navbar />
      <Head>
        <title>
          {slug ? slug.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ") : "Blog Post"} | Finovista
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="eventPostMain">
          <div>
            {
              routerData[route] ? routerData[route].api === "events" ? <SinglePostEvent /> : <SinglePost api={routerData[route].api} getData={routerData[route].getData} /> : <p>404</p>
            }
          </div>
          <div className="">
            <Sidebar />
          </div>
        </div>

        <Footer />
      </div>
    </div>
  );
};

export default blogPost;
