import { useRouter } from "next/router";
import Navbar from "../../components/Navbar";
import Head from "next/head";
import Footer from "../../components/Footer";
import Sidebar from "../../components/Sidebar";
import SinglePostService from "../../components/Service/SinglePostService";
import { useEffect, useState } from "react";
import SingleService from "../../components/Service/SingleService";
import Link from "next/link";
import RelatedPost from "../../components/RelatedPost";

const servicePost = () => {
  const router = useRouter();
  const [services, setServices] = useState([]);
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    const getEvents = async () => {
      try {
        const cate = await fetch("/api/category");
        let cateRes = await cate.json();
        setCategories(cateRes.category);
        const response = await fetch(`/api/services?limit=3`);
        let ress = await response.json();
        setServices(ress.services);
        setLoading(false);
      } catch (error) {
        setLoading(false);
        setError(true);
      }
    };
    getEvents();
  }, []);

  const { slug } = router.query;

  return (
    <div>
      <Navbar />
      <Head>
        <title>
          {slug ? slug.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ") : "Service Post"} | Finovista
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="eventPostMain">
          <div>
            <SinglePostService />
          </div>
          <div className="">
            <Sidebar />
          </div>
        </div>
        <RelatedPost type={"services"} link='service' data={services} loading={loading} />
        <Footer />
      </div>
    </div>
  );
};

export default servicePost;
