import React from 'react';
import Navbar from "../components/Utils/Navbar";
import Head from "next/head";
import Footer from "../components/Utils/Footer";
import Sidebar from "../components/Utils/Sidebar";

function carrers() {

    return (
        <div>
            <Navbar />
            <Head>
                <title>
                    Carrers | Finovista
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div>
                    <div className='grid grid-cols-1 gap-10  text-gray-700 my-10 mx-3 md:mx-12 lg:mx-24 xl:mx-32'>
                        <p className='text-lg font-semibold'>We’re building careers in public policy.
                            Our extraordinarily diverse team is driven by one belief – public policy, supported by deep analysis, can be a force for good.
                        </p>
                        <h2 className='text-2xl font-semibold'>
                            Open Positions
                        </h2>
                        <p className='-mt-8 text-sm'>
                            Finovista presents an opportunity to use your talent to solve pressing national and global issues. <span className='text-blue-500'>Read more in The Think Tank Route to Public Good</span>
                        </p>
                        <div className='grid grid-cols-3 gap-4'>
                            <div className='col-span-1 rounded-md shadow-md p-4'>
                                <h1 className='text-sm'>Why Finovista?</h1>
                                <p className='text-sm mt-4'>We’re building careers in public policy.
                                    Our extraordinarily diverse team is driven by one belief – public policy, supported by deep analysis, can be a force for good.
                                </p>
                            </div>
                            <div className='col-span-1 rounded-md shadow-md p-4'>
                                <h1 className='text-sm'>Why Finovista?</h1>
                                <p className='text-sm mt-4'>We’re building careers in public policy.
                                    Our extraordinarily diverse team is driven by one belief – public policy, supported by deep analysis, can be a force for good.
                                </p>
                            </div>
                            <div className='col-span-1 rounded-md shadow-md p-4'>
                                <h1 className='text-sm'>Why Finovista?</h1>
                                <p className='text-sm mt-4'>We’re building careers in public policy.
                                    Our extraordinarily diverse team is driven by one belief – public policy, supported by deep analysis, can be a force for good.
                                </p>
                            </div>
                            <div className='col-span-1 rounded-md shadow-md p-4'>
                                <h1 className='text-sm'>Why Finovista?</h1>
                                <p className='text-sm mt-4'>We’re building careers in public policy.
                                    Our extraordinarily diverse team is driven by one belief – public policy, supported by deep analysis, can be a force for good.
                                </p>
                            </div>
                            <div className='col-span-1 rounded-md shadow-md p-4'>
                                <h1 className='text-sm'>Why Finovista?</h1>
                                <p className='text-sm mt-4'>We’re building careers in public policy.
                                    Our extraordinarily diverse team is driven by one belief – public policy, supported by deep analysis, can be a force for good.
                                </p>
                            </div>
                            <div className='col-span-1 rounded-md shadow-md p-4'>
                                <h1 className='text-sm'>Why Finovista?</h1>
                                <p className='text-sm mt-4'>We’re building careers in public policy.
                                    Our extraordinarily diverse team is driven by one belief – public policy, supported by deep analysis, can be a force for good.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <Footer />
            </div>
        </div>
    )
}

export default carrers